### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by mehuls2905** [mehuls2905/Tasks#5]
If there will be task in huge number in todo list and if we have to find any task we can type in search box and can find it

**Comment by aswinikalyan30** [comment]
Can i take this up?

**Comment by Aniket-508** [comment]
@mehuls2905 I want to work on this issue. Pls assign it to me.

**Comment by mehuls2905** [comment]
You have already been assigned with Issue #2 @Aniket-508 . Sorry, i can only assign 1 issue at a time per participant until the issue is solved by the participant.
